# Generated by Django 6.0 on 2025-12-22 13:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayananTindakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tindakan', models.CharField(max_length=100)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kategori', models.CharField(choices=[('pemeriksaan', 'Pemeriksaan'), ('tindakan', 'Tindakan'), ('laboratorium', 'Laboratorium'), ('radiologi', 'Radiologi'), ('lainnya', 'Lainnya')], default='tindakan', max_length=50)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Layanan Tindakan',
                'db_table': 'layanan_tindakan',
            },
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('tablet', 'Tablet'), ('kapsul', 'Kapsul'), ('sirup', 'Sirup'), ('salep', 'Salep'), ('injeksi', 'Injeksi'), ('tetes', 'Tetes'), ('lainnya', 'Lainnya')], default='tablet', max_length=50)),
                ('stok', models.IntegerField(default=0)),
                ('satuan', models.CharField(choices=[('tablet', 'Tablet'), ('kapsul', 'Kapsul'), ('botol', 'Botol'), ('tube', 'Tube'), ('ampul', 'Ampul'), ('strip', 'Strip'), ('box', 'Box')], default='tablet', max_length=50)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Obat',
                'db_table': 'obat',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin Klinik'), ('dokter', 'Dokter'), ('pasien', 'Pasien'), ('resepsionis', 'Resepsionis'), ('apoteker', 'Apoteker'), ('kasir', 'Kasir')], default='pasien', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('foto_profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'custom_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Apoteker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_sipa', models.CharField(max_length=50, unique=True, verbose_name='No. SIPA')),
                ('tanggal_mulai_kerja', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apoteker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Apoteker',
                'db_table': 'apoteker',
            },
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spesialisasi', models.CharField(choices=[('umum', 'Dokter Umum'), ('gigi', 'Dokter Gigi'), ('anak', 'Dokter Anak'), ('kandungan', 'Dokter Kandungan'), ('mata', 'Dokter Mata'), ('tht', 'Dokter THT'), ('kulit', 'Dokter Kulit'), ('jantung', 'Dokter Jantung'), ('bedah', 'Dokter Bedah'), ('saraf', 'Dokter Saraf')], default='umum', max_length=50)),
                ('no_str', models.CharField(max_length=50, unique=True, verbose_name='No. STR')),
                ('jadwal_praktik', models.JSONField(blank=True, default=dict)),
                ('biaya_konsultasi', models.DecimalField(decimal_places=2, default=100000, max_digits=12)),
                ('status_aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dokter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dokter',
                'db_table': 'dokter',
            },
        ),
        migrations.CreateModel(
            name='Kasir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai_kerja', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kasir_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kasir',
                'db_table': 'kasir',
            },
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rm', models.CharField(max_length=20, unique=True, verbose_name='No. Rekam Medis')),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('golongan_darah', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('alergi', models.TextField(blank=True, null=True)),
                ('kontak_darurat', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pasien_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pasien',
                'db_table': 'pasien',
            },
        ),
        migrations.CreateModel(
            name='JanjiTemu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('keluhan', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Terkonfirmasi'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('nomor_antrian', models.IntegerField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='janji_temu', to='core.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='janji_temu', to='core.pasien')),
            ],
            options={
                'verbose_name_plural': 'Janji Temu',
                'db_table': 'janji_temu',
                'ordering': ['-tanggal', 'waktu'],
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(choices=[('tunai', 'Tunai'), ('transfer', 'Transfer Bank'), ('asuransi', 'Asuransi'), ('qris', 'QRIS')], default='tunai', max_length=20)),
                ('total_biaya', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('biaya_konsultasi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('biaya_obat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('biaya_tindakan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tanggal_bayar', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Belum Lunas'), ('lunas', 'Lunas')], default='pending', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('janji_temu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='core.janjitemu')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_processed', to='core.kasir')),
            ],
            options={
                'verbose_name_plural': 'Pembayaran',
                'db_table': 'pembayaran',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RekamMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosa', models.TextField()),
                ('anamnesa', models.TextField(verbose_name='Anamnesa/Keluhan')),
                ('pemeriksaan_fisik', models.TextField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tanggal_periksa', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekam_medis', to='core.dokter')),
                ('janji_temu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rekam_medis', to='core.janjitemu')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekam_medis', to='core.pasien')),
                ('tindakan', models.ManyToManyField(blank=True, related_name='rekam_medis', to='core.layanantindakan')),
            ],
            options={
                'verbose_name_plural': 'Rekam Medis',
                'db_table': 'rekam_medis',
                'ordering': ['-tanggal_periksa'],
            },
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_resep', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Proses'), ('processed', 'Sedang Diproses'), ('delivered', 'Sudah Diserahkan')], default='pending', max_length=20)),
                ('catatan_apoteker', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resep_processed', to='core.apoteker')),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resep', to='core.rekammedis')),
            ],
            options={
                'verbose_name_plural': 'Resep',
                'db_table': 'resep',
                'ordering': ['-tanggal_resep'],
            },
        ),
        migrations.CreateModel(
            name='DetailResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=1)),
                ('aturan_pakai', models.CharField(max_length=200)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_resep', to='core.obat')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_resep', to='core.resep')),
            ],
            options={
                'verbose_name_plural': 'Detail Resep',
                'db_table': 'detail_resep',
            },
        ),
        migrations.CreateModel(
            name='Resepsionis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('pagi', 'Pagi (07:00 - 14:00)'), ('siang', 'Siang (14:00 - 21:00)'), ('malam', 'Malam (21:00 - 07:00)')], default='pagi', max_length=20)),
                ('tanggal_mulai_kerja', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resepsionis_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resepsionis',
                'db_table': 'resepsionis',
            },
        ),
    ]
