# Generated by Django 6.0 on 2025-12-28 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('object_str', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Cicilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_cicilan', models.IntegerField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('tanggal_bayar', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Belum Dibayar'), ('lunas', 'Lunas'), ('overdue', 'Terlambat')], default='pending', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cicilan',
                'ordering': ['nomor_cicilan'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoice_qr_code',
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('janji_temu', 'Janji Temu'), ('resep', 'Resep'), ('pembayaran', 'Pembayaran'), ('antrian', 'Antrian'), ('rekam_medis', 'Rekam Medis'), ('stok', 'Stok Obat'), ('system', 'System')], max_length=50)),
                ('judul', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifikasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock_transfer', 'Mock Transfer Bank'), ('mock_qris', 'Mock QRIS'), ('mock_ewallet', 'Mock E-Wallet'), ('mock_cc', 'Mock Credit Card')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_gateway',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StokAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('reason', models.CharField(choices=[('opname', 'Opname'), ('rusak', 'Rusak'), ('kadaluarsa', 'Kadaluarsa'), ('koreksi', 'Koreksi'), ('lainnya', 'Lainnya')], max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stok_adjustment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='waktu_mulai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='waktu_selesai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='rekammedis',
            constraint=models.UniqueConstraint(condition=models.Q(('janji_temu__isnull', False)), fields=('janji_temu',), name='unique_rekam_medis_per_janji'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cicilan',
            name='pembayaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cicilan', to='core.pembayaran'),
        ),
        migrations.AddField(
            model_name='invoiceqrcode',
            name='pembayaran',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='core.pembayaran'),
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.paymentgateway'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='pembayaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.pembayaran'),
        ),
        migrations.AddField(
            model_name='stokadjustment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stokadjustment',
            name='obat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_adjustments', to='core.obat'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='audit_log_user_id_79f582_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='audit_log_model_n_c04ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='notifikasi',
            index=models.Index(fields=['user', '-created_at'], name='notifikasi_user_id_7eb7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='notifikasi',
            index=models.Index(fields=['user', 'is_read'], name='notifikasi_user_id_00961b_idx'),
        ),
    ]
