# Generated by Django 6.0 on 2025-12-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_cicilan_invoiceqrcode_notifikasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_hint',
            field=models.CharField(blank=True, help_text='Password hint untuk admin', max_length=255, null=True),
        ),
    ]
