# Generated by Django 6.0 on 2025-12-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_password_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janjitemu',
            name='nomor_antrian',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
